set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" add all your plugins here (note older versions of Vundle
" used Bundle instead of Plugin)
Plugin 'tmhedberg/SimpylFold'
"Plugin 'vim-scripts/indentpython.vim'
"Plugin 'Valloric/YouCompleteMe'
Plugin 'vim-syntastic/syntastic'  " Syntax checking
"Plugin 'nvie/vim-flake8'
Plugin 'jnurmine/Zenburn'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'kien/ctrlp.vim'
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
"Plugin 'vim-scripts/vim-auto-save'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-unimpaired'
"Plugin 'majutsushi/tagbar'
Plugin 'davidhalter/jedi-vim'
" Plugin 'ludovicchabant/vim-gutentags'
" Plugin 'neovimhaskell/haskell-vim'
" Plugin 'dbeniamine/cheat.sh-vim'
" Plugin 'nbouscal/vim-stylish-haskell'
" Plugin 'elmcast/elm-vim'
Plugin 'tpope/vim-abolish'
" Plugin 'posva/vim-vue'
" Plugin 'prettier/vim-prettier'
Plugin 'editorconfig/editorconfig-vim'
" Plugin 'slashmili/alchemist.vim'
" Plugin 'elixir-editors/vim-elixir'
" Plugin 'mhinz/vim-mix-format'
Plugin 'sheerun/vim-polyglot'  " Syntax higlighting
Plugin 'dense-analysis/ale'
Plugin 'jmcantrell/vim-virtualenv'
Plugin 'codota/tabnine-vim'  " Autocomplete

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

